import { ParamKind } from "./ddxParamKind";
export const COMPRESSOR_PARAMS = [
  {
    id: 40,
    key: "compOn",
    label: "Compressor On",
    kind: ParamKind.SWITCH,
    classSelected: "btn-success",
    defaultRaw: 0, // 0/1 (or use true/false if you prefer)
    format: (v) => (v ? "On" : "Off"),
  },
  {
    id: 41,
    key: "compKey",
    label: "Compressor Key Source",
    kind: ParamKind.ENUM,
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    labels: Object.fromEntries([
      [0, "Self / Sum"],
      ...Array.from({ length: 16 }, (_, i) => [i + 1, `Ch ${i + 1}`]),
    ]),
    defaultRaw: 0,
    format: (v, def) => def.labels?.[v] ?? String(v),
  },
  {
    id: 42,
    key: "compAttack",
    label: "Compressor Attack",
    kind: ParamKind.RANGE,
    min: 0,
    max: 200,
    defaultRaw: 0,
    format: (v) => `${v} ms`,
  },
  {
    id: 43,
    key: "compRelease",
    label: "Compressor Release",
    kind: ParamKind.RANGE,
    min: 0,
    max: 255,
    defaultRaw: 0,
    format: (v) => {
      const ms = 20 * Math.pow(250, v / 255);
      return `${ms.toFixed(1)} ms`;
    },
  },
  {
    id: 44,
    key: "compRatio",
    label: "Compressor Ratio",
    kind: ParamKind.ENUM,
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    labels: {
      0: "1.0",
      1: "1.2",
      2: "1.4",
      3: "1.6",
      4: "1.8",
      5: "2.0",
      6: "2.5",
      7: "3.0",
      8: "3.5",
      9: "4.0",
      10: "5.0",
      11: "6.0",
      12: "8.0",
      13: "10.0",
      14: "20.0",
      15: "100.0",
    },
    defaultRaw: 0,
  },
  {
    id: 45,
    key: "compKnee",
    label: "Compressor Knee",
    kind: ParamKind.RANGE,
    min: 0,
    max: 5,
    defaultRaw: 0,
    format: (v) => String(v),
  },
  {
    id: 46,
    key: "compThreshold",
    label: "Compressor Threshold",
    kind: ParamKind.RANGE,
    min: 0,
    max: 60,
    defaultRaw: 60,
    format: (v) => `${-60 + v} dB`,
  },
  {
    id: 47,
    key: "compGain",
    label: "Compressor Gain",
    kind: ParamKind.RANGE,
    min: 0,
    max: 24,
    defaultRaw: 0,
    format: (v) => `${v} dB`,
  },
];
